-- Touch Grass — Supabase schema
-- Run this in the Supabase SQL editor, then copy the project URL and anon key
-- into your .env (see .env.example).
--
-- The whole file is idempotent: safe to run on a fresh project OR re-run on an
-- existing one to upgrade it (e.g. to add the social features: accounts,
-- spot ownership, comments).

-- 1. Category enum ----------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'spot_category') then
    create type spot_category as enum (
      'food',
      'cafe',
      'bar',
      'park',
      'nature',
      'viewpoint',
      'activity',
      'culture',
      'shopping',
      'other'
    );
  end if;
end$$;

-- 2. Profiles (one per auth user) --------------------------------------------
create table if not exists profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  username   text not null unique check (username ~ '^[a-zA-Z0-9_]{3,20}$'),
  created_at timestamptz not null default now()
);

alter table profiles enable row level security;

drop policy if exists "public read profiles" on profiles;
create policy "public read profiles" on profiles
  for select using (true);

drop policy if exists "users insert own profile" on profiles;
create policy "users insert own profile" on profiles
  for insert to authenticated with check (auth.uid() = id);

drop policy if exists "users update own profile" on profiles;
create policy "users update own profile" on profiles
  for update to authenticated using (auth.uid() = id);

-- Auto-create a profile when someone signs up. The username is passed as
-- user metadata by the app's sign-up form; fall back to a generated handle.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'username', ''),
      'explorer_' || substr(replace(new.id::text, '-', ''), 1, 8)
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 3. Spots table --------------------------------------------------------------
create table if not exists "Spots" (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text not null default '',
  category    spot_category,
  tags        text[] not null default '{}',
  image_url   text[] not null default '{}',
  -- { "latitude": number, "longitude": number }
  location    jsonb,
  created_at  timestamptz not null default now()
);

-- Ownership (added for the social upgrade; legacy rows keep user_id = null).
alter table "Spots"
  add column if not exists user_id uuid references profiles (id) on delete set null
  default auth.uid();

-- 4. Comments -----------------------------------------------------------------
create table if not exists "Comments" (
  id         bigint generated by default as identity primary key,
  spot_id    bigint not null references "Spots" (id) on delete cascade,
  user_id    uuid not null references profiles (id) on delete cascade
             default auth.uid(),
  content    text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists comments_spot_idx on "Comments" (spot_id, created_at);

-- 5. Row level security --------------------------------------------------------
alter table "Spots" enable row level security;

drop policy if exists "public read spots" on "Spots";
create policy "public read spots" on "Spots"
  for select using (true);

-- Anonymous inserts are no longer allowed: pinning a spot requires an account.
drop policy if exists "public insert spots" on "Spots";
drop policy if exists "authenticated insert spots" on "Spots";
create policy "authenticated insert spots" on "Spots"
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "owners update spots" on "Spots";
create policy "owners update spots" on "Spots"
  for update to authenticated using (auth.uid() = user_id);

drop policy if exists "owners delete spots" on "Spots";
create policy "owners delete spots" on "Spots"
  for delete to authenticated using (auth.uid() = user_id);

alter table "Comments" enable row level security;

drop policy if exists "public read comments" on "Comments";
create policy "public read comments" on "Comments"
  for select using (true);

drop policy if exists "authenticated insert comments" on "Comments";
create policy "authenticated insert comments" on "Comments"
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "owners delete comments" on "Comments";
create policy "owners delete comments" on "Comments"
  for delete to authenticated using (auth.uid() = user_id);

-- 6. RPC used by the Add Spot form to populate the category dropdown ----------
create or replace function get_category_enum_values()
returns text[]
language sql
stable
as $$
  select array(
    select unnest(enum_range(null::spot_category))::text
  );
$$;

grant execute on function get_category_enum_values() to anon;
grant execute on function get_category_enum_values() to authenticated;

-- 7. Storage bucket for spot photos -------------------------------------------
-- Photos live at "<user-id>/<timestamp>.jpg". Anyone can view; signed-in
-- users can only write inside the folder named after their own user id, so
-- nobody can overwrite or delete someone else's photos.
insert into storage.buckets (id, name, public)
values ('location-images', 'location-images', true)
on conflict (id) do nothing;

drop policy if exists "public read location-images" on storage.objects;
create policy "public read location-images" on storage.objects
  for select using (bucket_id = 'location-images');

drop policy if exists "public upload location-images" on storage.objects;
drop policy if exists "authenticated upload location-images" on storage.objects;
create policy "authenticated upload location-images" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'location-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "owners delete location-images" on storage.objects;
create policy "owners delete location-images" on storage.objects
  for delete to authenticated using (
    bucket_id = 'location-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- 8. Migration: image paths, not URLs ------------------------------------------
-- Spots.image_url now stores storage *paths* (e.g. "user-id/1720000000.jpg");
-- the app builds full URLs from one base-URL config value. Strip the host
-- prefix off any legacy rows that stored complete public URLs.
update "Spots"
set image_url = (
  select coalesce(
    array_agg(
      regexp_replace(
        u,
        '^https?://[^/]+/storage/v1/object/public/location-images/',
        ''
      )
    ),
    '{}'
  )
  from unnest(image_url) as u
)
where exists (select 1 from unnest(image_url) as u where u like 'http%');
