-- Touch Grass — Supabase schema
-- Run this in the Supabase SQL editor on a fresh project, then copy the
-- project URL and anon key into your .env (see .env.example).
--
-- The app has no authentication yet, so the policies below allow the anon role
-- to read and insert spots. Tighten these once you add auth.

-- 1. Category enum ----------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'spot_category') then
    create type spot_category as enum (
      'food',
      'cafe',
      'bar',
      'park',
      'nature',
      'viewpoint',
      'activity',
      'culture',
      'shopping',
      'other'
    );
  end if;
end$$;

-- 2. Spots table ------------------------------------------------------------
create table if not exists "Spots" (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text not null default '',
  category    spot_category,
  tags        text[] not null default '{}',
  image_url   text[] not null default '{}',
  -- { "latitude": number, "longitude": number }
  location    jsonb,
  created_at  timestamptz not null default now()
);

-- 3. Row level security -----------------------------------------------------
alter table "Spots" enable row level security;

drop policy if exists "public read spots" on "Spots";
create policy "public read spots" on "Spots"
  for select using (true);

drop policy if exists "public insert spots" on "Spots";
create policy "public insert spots" on "Spots"
  for insert with check (true);

-- 4. RPC used by the Add Spot form to populate the category dropdown --------
create or replace function get_category_enum_values()
returns text[]
language sql
stable
as $$
  select array(
    select unnest(enum_range(null::spot_category))::text
  );
$$;

grant execute on function get_category_enum_values() to anon;

-- 5. Storage bucket for spot photos -----------------------------------------
insert into storage.buckets (id, name, public)
values ('location-images', 'location-images', true)
on conflict (id) do nothing;

drop policy if exists "public read location-images" on storage.objects;
create policy "public read location-images" on storage.objects
  for select using (bucket_id = 'location-images');

drop policy if exists "public upload location-images" on storage.objects;
create policy "public upload location-images" on storage.objects
  for insert with check (bucket_id = 'location-images');
